version = "1.0"

[main]
name = "Kavita Email configuration"
services = ["__APP__"]

    [main.config]
    name = "Configuration Options"
    
        [main.config.smtp_host]
        ask = "Edit SMTP Host"
        type = "string"
        help = "Edit SMTP Host"
        
        [main.config.smtp_port]
        ask = "Edit SMTP Port"
        type = "number"
        help = "Edit SMTP Port"
        bind = "smtp_port:/var/www/__APP__/config/appsettings.json"

        [main.config.smtp_username]
        ask = "Edit SMTP Username"
        type = "string"
        help = "Edit SMTP Username"
        bind = "smtp_username:/var/www/__APP__/config/appsettings.json"
        
        [main.config.smtp_password]
        ask = "Edit SMTP Password"
        type = "password"
        help = "Edit SMTP Password"
        bind = "smtp_password:/var/www/__APP__/config/appsettings.json"
        
        [main.config.smtp_sender_address]
        ask = "Edit SMTP Sender address"
        type = "string"
        help = "Edit SMTP Sender address"
        bind = "smtp_sender_address:/var/www/__APP__/config/appsettings.json"
