version = "1.0"

[main]
name = "__APP__ configuration"

    [main.options]
    name = "Configuration Options"
    
        [main.options.SMTP_HOST]
        ask = "Edit SMTP Host"
        type = "string"
        help = "Edit SMTP Host"
        bind = "SMTP_HOST:__FINALPATH__/config/appsettings.json"
        services = [ '__APP__' ]
        
        [main.options.SMTP_port]
        ask = "Edit SMTP Port"
        type = "number"
        help = "Edit SMTP Port"
        bind = "SMTP_port:__FINALPATH__/config/appsettings.json"
        services = [ '__APP__' ]

        [main.options.SMTP_USERNAME]
        ask = "Edit SMTP Username"
        type = "string"
        help = "Edit SMTP Username"
        bind = "SMTP_USERNAME:__FINALPATH__/config/appsettings.json"
        services = [ '__APP__' ]
        
        [main.options.SMTP_PASSWORD]
        ask = "Edit SMTP Password"
        type = "password"
        help = "Edit SMTP Password"
        bind = "SMTP_PASSWORD:__FINALPATH__/config/appsettings.json"
        services = [ '__APP__' ]
        
        [main.options.SMTP_SENDER_ADDRESS]
        ask = "Edit SMTP Sender address"
        type = "string"
        help = "Edit SMTP Sender address"
        bind = "SMTP_SENDER_ADDRESS:__FINALPATH__/config/appsettings.json"
        services = [ '__APP__' ]
