packaging_format = 2

id = "kavitaemail"
name = "Kavita Email"
description.en = "This is a simple email relay server that handles emails from Kavita application"
description.fr = "TBA"

version = "0.1.19.0~ynh1"

maintainers = ["TBA"]

[upstream]
license = "MIT"
website = "https://kavitareader.com/"
admindoc = "https://wiki.kavitareader.com/en/guides/misc/email"
code = "https://github.com/Kareadita/KavitaEmail"
cpe = "TBA"
fund = "https://opencollective.com/Kavita#backer"

[integration]
yunohost = ">= 11.1.19"
architectures = ["amd64", "arm64", "armhf"]
multi_instance = false
ldap = "not_relevant"
sso = "not_relevant"
disk = "50M"
ram.build = "150M"
ram.runtime = "250M"

[install]    
    [install.smtp_host]
    ask = "Edit SMTP Host"
    type = "string"
    #default = ""
    help = "Edit SMTP Host"

    [install.smtp_port]
    ask = "Edit SMTP Port"
    type = "number"
    default = "25"
    help = "Edit SMTP Port"

    [install.smtp_username]
    ask = "Edit SMTP Username"
    type = "string"
    #default = ""
    help = "Edit SMTP Username"

    [install.smtp_password]
    help.en = "Enter SMTP password"
    help.fr = "Entrer le mot de passe RCON"
    type = "password"

    [install.smtp_sender_address]
    ask = "Edit SMTP Sender address"
    type = "string"
    #default = ""
    help = "Edit SMTP Sender address"

[resources]

 [resources.sources]
    [resources.sources.main]
    in_subdir = true
    armhf.url = "https://github.com/Kareadita/KavitaEmail/releases/download/v0.1.19.0/kavitaemail-linux-arm.tar.gz"
    armhf.sha256 = "tba"
    amd64.url = "https://github.com/Kareadita/KavitaEmail/releases/download/v0.1.19.0/kavitaemail-linux-x64.tar.gz"
    amd64.sha256 = "601e4cc52cc28650b63525e68763c04eb8ea97730b445f36db9801ee9ad89fb1"
    arm64.url = "https://github.com/Kareadita/KavitaEmail/releases/download/v0.1.19.0/kavitaemail-linux-arm64.tar.gz"
    arm64.sha256 = "69950777857aa498b507e89bde0b711b707d117b2c60293b49e8da9851b10d9d"

    [resources.ports]
    main.default = 5003

    [resources.system_user]

    [resources.install_dir]

    [resources.permissions]
