packaging_format = 2

id = "KavitaEmail"
name = "Kavita Email"
description.en = "This is a simple email relay server that handles emails from Kavita application"
description.fr = "TBA"

version = "0.1.19.0~ynh1"

maintainers = ["TBA"]

[upstream]
license = "MIT"
website = "https://kavitareader.com/"
admindoc = "https://wiki.kavitareader.com/en/guides/misc/email"
code = "https://github.com/Kareadita/KavitaEmail"
cpe = "TBA"
fund = "https://opencollective.com/Kavita#backer"

[integration]
yunohost = ">= 11.1.19"
architectures = ["amd64", "arm64", "armhf"]
multi_instance = false
ldap = "not_relevant"
sso = "not_relevant"
disk = "50M"
ram.build = "150M"
ram.runtime = "50M"

[install]

[resources]

 [resources.sources]
    [resources.sources.main]
    in_subdir = true
    armhf.url = "https://github.com/Kareadita/KavitaEmail/releases/download/v0.1.19.0/kavitaemail-linux-arm.tar.gz"
    armhf.sha256 = "tba"
    amd64.url = "https://github.com/Kareadita/KavitaEmail/releases/download/v0.1.19.0/kavitaemail-linux-x64.tar.gz"
    amd64.sha256 = "tba"
    arm64.url = "https://github.com/Kareadita/KavitaEmail/releases/download/v0.1.19.0/kavitaemail-linux-arm64.tar.gz"
    arm64.sha256 = "tba"

    [resources.ports]
    main.default = 5003

    [resources.system_user]

    [resources.install_dir]

    [resources.permissions]
