#!/bin/bash

#=================================================
# GENERIC START
#=================================================
# IMPORT GENERIC HELPERS
#=================================================
source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# RETRIEVE ARGUMENTS FROM THE MANIFEST
#=================================================
smtp_host=""
smtp_port=22
smtp_username=""
smtp_password=""
smtp_sender_address=""

#=================================================
# STORE SETTINGS FROM MANIFEST
#=================================================
ynh_app_setting_set --app=$app --key=smtp_host --value=$smtp_host
ynh_app_setting_set --app=$app --key=smtp_port --value=$smtp_port
ynh_app_setting_set --app=$app --key=smtp_username --value=$smtp_username
ynh_app_setting_set --app=$app --key=smtp_password --value=$smtp_password
ynh_app_setting_set --app=$app --key=smtp_sender_address --value=$smtp_sender_address

#=================================================
# CHECK VERSION
#=================================================

upgrade_type=$(ynh_check_app_version_changed)

#=================================================
# STANDARD UPGRADE STEPS
#=================================================
# STOP SYSTEMD SERVICE
#=================================================
ynh_script_progression --message="Stopping a systemd service..." --weight=1

ynh_systemd_action --service_name=$app --action="stop" --log_path="/var/log/$app/$app.log"

#=================================================
# DOWNLOAD, CHECK AND UNPACK SOURCE
#=================================================

if [ "$upgrade_type" == "UPGRADE_APP" ]
then
	ynh_script_progression --message="Upgrading source files..." --weight=1

	# Download, check integrity, uncompress and patch the source from app.src
	ynh_setup_source --dest_dir="$install_dir"
fi

chmod -R o-rwx "$install_dir"
chown -R $app:$app "$install_dir"
chmod +x $install_dir/KavitaEmail

#=================================================
# MODIFY A CONFIG FILE
#=================================================
ynh_script_progression --message="Modifying a config file..." --weight=1

key=$(ynh_string_random --length=176)
url_path=${path#/}
ynh_add_config --template="../conf/appsettings.json.example" --destination="$install_dir/config/appsettings.json"

chmod 600 "$install_dir/config/appsettings.json"
chown $app:$app "$install_dir/config/appsettings.json"

#=================================================
# REAPPLY SYSTEM CONFIGURATIONS
#=================================================
ynh_script_progression --message="Upgrading system configurations related to $app..." --weight=4

# Create a dedicated systemd config
ynh_add_systemd_config

yunohost service add $app --description="Messaging platform" --log="/var/log/$app/$app.log" --needs_exposed_ports="$port"

#=================================================
# START SYSTEMD SERVICE
#=================================================
ynh_script_progression --message="Starting a systemd service..." --weight=1

ynh_systemd_action --service_name=$app --action="start" --log_path="/var/log/$app/$app.log"

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression --message="Upgrade of $app completed" --last
